name: Hola mundo 

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout el código 
      uses: actions/checkout@v2

    - name: Imprimir Hola, mundo
      run: echo "Hola, mundo"
